# Generated by Django 5.1.6 on 2025-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itstepproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=80, verbose_name='Название компании'),
        ),
    ]
