# Generated by Django 5.1.6 on 2025-03-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itstepproject', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия(2)', 'verbose_name_plural': 'Вакансии(2)'},
        ),
    ]
